<?php
// Dữ liệu mẫu

$users = [
    [
        'id' => 1,
        'name' => 'John Doe',
        'email' => 'john@gmail.com',
        'phone' => '0909090909',
        'address' => '123 adress',
        'city' => 'city 1',
        'district' => 'district 1',
        'ward' => 'ward 1',
    ]
];

$user = [
    'id' => 1,
    'name' => 'John Doe',
    'email' => 'john@gmail.com',
    'phone' => '0909090909',
    'address' => '123 adress',
    'city' => 'city 1',
    'district' => 'district 1',
    'ward' => 'ward 1',
];

$payment_methods = [
    [
        'id' => 1,
        'name' => 'Tiền mặt'
    ],
    [
        'id' => 2,
        'name' => 'Trực tuyến'
    ]
];

$categories = [
    [
        'id' => 1,
        'name' => 'Tâm lý - Kỹ năng sống'
    ],
    [
        'id' => 2,
        'name' => 'Tiểu thuyết'
    ],
    [
        'id' => 4,
        'name' => 'Kỹ năng sống'
    ],
    [
        'id' => 5,
        'name' => 'Văn học Việt Nam'
    ],
    [
        'id' => 6,
        'name' => 'Văn học nước ngoài'
    ],
    [
        'id' => 7,
        'name' => 'Văn học Nhật Bản'
    ],
    [
        'id' => 8,
        'name' => 'Kỹ năng giao tiếp'
    ],
    [
        'id' => 9,
        'name' => 'Lịch sử - Khoa học'
    ],
    [
        'id' => 10,
        'name' => 'Kinh tế tài chính'
    ],
];


$orders = [
    [
        'id' => 1,
        'order_date' => '2024-01-01',
        'total_amount' => '210.000',
        'status' => 'pending',
        'payment_method' => 'Chuyển khoản',
        'address' => '123 adress',
        'city' => 'city 1',
        'district' => 'district 1',
        'ward' => 'ward 1',
        'details' => [
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 1,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 2,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ]
        ],
    ],
    [
        'id' => 2,
        'order_date' => '2024-01-01',
        'total_amount' => '210.000',
        'status' => 'confirmed',
        'payment_method' => 'Tiền mặt',
        'address' => '123 adress',
        'city' => 'city 1',
        'district' => 'district 1',
        'ward' => 'ward 1',
        'details' => [
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 1,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 2,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ]
        ],
    ],
    [
        'id' => 3,
        'order_date' => '2024-01-01',
        'total_amount' => '210.000',
        'status' => 'canceled',
        'payment_method' => 'Tiền mặt',
        'address' => '123 adress',
        'city' => 'city 1',
        'district' => 'district 1',
        'ward' => 'ward 1',
        'details' => [
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 1,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 2,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ]
        ],
    ],
    [
        'id' => 4,
        'order_date' => '2024-01-01',
        'total_amount' => '210.000',
        'status' => 'delivered_success',
        'payment_method' => 'Tiền mặt',
        'address' => '123 adress',
        'city' => 'city 1',
        'district' => 'district 1',
        'ward' => 'ward 1',
        'details' => [
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 1,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 2,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 3,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 4,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 5,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 6,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 7,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 8,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 9,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 10,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 11,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 12,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
        ],
    ],
    [
        'id' => 5,
        'order_date' => '2024-01-01',
        'total_amount' => '210.000',
        'status' => 'delivered_success',
        'payment_method' => 'Tiền mặt',
        'address' => '123 adress',
        'city' => 'city 1',
        'district' => 'district 1',
        'ward' => 'ward 1',
        'details' => [
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 1,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 2,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 3,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 4,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 5,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '90.000',
                'book' =>
                    [
                        'id' => 6,
                        'name' => 'Nhà Giả Kim',
                        'category' => 'Tiểu thuyết',
                        'author' => 'Paulo Coelho',
                        'publisher' => 'NXB',
                        'price' => '90.000',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
            [
                'quantity' => 1,
                'price' => '120.000',
                'book' =>
                    [
                        'id' => 7,
                        'name' => 'Đắc Nhân Tâm',
                        'category' => 'Tâm lý - Kỹ năng sống',
                        'author' => 'Dale Carnegie',
                        'publisher' => 'NXB',
                        'image' => '../../img/b002.png',
                        'description' => 'Mô tả sách',
                        'length' => 20,
                        'weight' => 0.5,
                        'dimensions' => '20x15 cm',
                        'language' => 'Tiếng việt',
                        'format' => 'Bìa mềm',
                        'release_date' => '2024-01-01',
                    ]
            ],
        ],
    ],
];

$best_seller_books = [
    [
        'id' => 1,
        'name' => 'Đắc Nhân Tâm',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'Dale Carnegie',
        'publisher' => 'NXB',
        'price' => '120.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 0,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 2,
        'name' => 'Nhà Giả Kim',
        'category' => 'Tiểu thuyết',
        'author' => 'Paulo Coelho',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 3,
        'name' => 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
        'category' => 'Kỹ năng sống',
        'author' => 'Rosie Nguyễn',
        'publisher' => 'NXB',
        'price' => '85.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 4,
        'name' => 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh',
        'category' => 'Văn học Việt Nam',
        'author' => 'Nguyễn Nhật Ánh',
        'publisher' => 'NXB',
        'price' => '75.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
];

$books = [
    [
        'id' => 1,
        'name' => 'Đắc Nhân Tâm',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'Dale Carnegie',
        'publisher' => 'NXB',
        'price' => '120.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 2,
        'name' => 'Nhà Giả Kim',
        'category' => 'Tiểu thuyết',
        'author' => 'Paulo Coelho',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 3,
        'name' => 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
        'category' => 'Kỹ năng sống',
        'author' => 'Rosie Nguyễn',
        'publisher' => 'NXB',
        'price' => '85.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 4,
        'name' => 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh',
        'category' => 'Văn học Việt Nam',
        'author' => 'Nguyễn Nhật Ánh',
        'publisher' => 'NXB',
        'price' => '75.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 5,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 6,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 7,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 0,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 8,
        'name' => 'Tư Duy Phản Biện',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'Richard Paul & Linda Elder',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 6,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 7,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 8,
        'name' => 'Tư Duy Phản Biện',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'Richard Paul & Linda Elder',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 6,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 7,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 8,
        'name' => 'Tư Duy Phản Biện',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'Richard Paul & Linda Elder',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 6,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 7,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 8,
        'name' => 'Tư Duy Phản Biện',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'Richard Paul & Linda Elder',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 6,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 7,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 8,
        'name' => 'Tư Duy Phản Biện',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'Richard Paul & Linda Elder',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 9,
        'name' => 'Khéo Ăn Nói Sẽ Có Được Thiên Hạ',
        'category' => 'Kỹ năng giao tiếp',
        'author' => 'Trác Nhã',
        'publisher' => 'NXB',
        'price' => '99.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 10,
        'name' => 'Đàn Ông Sao Hỏa Đàn Bà Sao Kim',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'John Gray',
        'publisher' => 'NXB',
        'price' => '118.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 11,
        'name' => 'Sapiens: Lược Sử Loài Người',
        'category' => 'Lịch sử - Khoa học',
        'author' => 'Yuval Noah Harari',
        'publisher' => 'NXB',
        'price' => '189.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 12,
        'name' => 'Nghĩ Giàu Làm Giàu',
        'category' => 'Kinh tế - Tài chính',
        'author' => 'Napoleon Hill',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 2,
        'name' => 'Nhà Giả Kim',
        'category' => 'Tiểu thuyết',
        'author' => 'Paulo Coelho',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 311,
        'name' => 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
        'category' => 'Kỹ năng sống',
        'author' => 'Rosie Nguyễn',
        'publisher' => 'NXB',
        'price' => '85.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 411,
        'name' => 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh',
        'category' => 'Văn học Việt Nam',
        'author' => 'Nguyễn Nhật Ánh',
        'publisher' => 'NXB',
        'price' => '75.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1

    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 511,
        'name' => 'Cây Cam Ngọt Của Tôi',
        'category' => 'Văn học nước ngoài',
        'author' => 'José Mauro de Vasconcelos',
        'publisher' => 'NXB',
        'price' => '108.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 611,
        'name' => 'Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya',
        'category' => 'Văn học Nhật Bản',
        'author' => 'Higashino Keigo',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 711,
        'name' => 'Atomic Habits',
        'category' => 'Kỹ năng sống',
        'author' => 'James Clear',
        'publisher' => 'NXB',
        'price' => '155.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 118,
        'name' => 'Tư Duy Phản Biện',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'Richard Paul & Linda Elder',
        'publisher' => 'NXB',
        'price' => '90.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 911,
        'name' => 'Khéo Ăn Nói Sẽ Có Được Thiên Hạ',
        'category' => 'Kỹ năng giao tiếp',
        'author' => 'Trác Nhã',
        'publisher' => 'NXB',
        'price' => '99.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 1110,
        'name' => 'Đàn Ông Sao Hỏa Đàn Bà Sao Kim',
        'category' => 'Tâm lý - Kỹ năng sống',
        'author' => 'John Gray',
        'publisher' => 'NXB',
        'price' => '118.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 1111,
        'name' => 'Sapiens: Lược Sử Loài Người',
        'category' => 'Lịch sử - Khoa học',
        'author' => 'Yuval Noah Harari',
        'publisher' => 'NXB',
        'price' => '189.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ],
    [
        'id' => 1112,
        'name' => 'Nghĩ Giàu Làm Giàu',
        'category' => 'Kinh tế - Tài chính',
        'author' => 'Napoleon Hill',
        'publisher' => 'NXB',
        'price' => '110.000',
        'image' => '../../img/b002.png',
        'description' => 'Mô tả sách',
        'stock' => 50,
        'length' => 20,
        'weight' => 0.5,
        'dimensions' => '20x15 cm',
        'language' => 'Tiếng việt',
        'format' => 'Bìa mềm',
        'release_date' => '2024-01-01',
        'status' => 1
    ]
];

$data = [
    'users' => $users,
    'user' => $user,
    'payment_methods' => $payment_methods,
    'categories' => $categories,
    'best_seller_books' => $best_seller_books,
    'books' => $books,
    'orders' => $orders,
];

?>